### ISSUE TITLE
No Transitions

### ISSUE THREAD

**Issue by nathasm** [danielepiccone/ng-pageslide#10]
I've been playing around with the ng-pageslide directive on a personal project and I can't seem to get the transitions to work. Basically upon showing, there is a delay and then the sidebar is displayed. And upon hiding it, it is immediately hidden.

I've created a plnkr to demonstrate what I'm seeing: 

http://plnkr.co/edit/0TaPxAsMZ7DO090WWH6Z?p=preview

Any thoughts on what could be the issue? I've played with different versions of angular, used foundation instead of bootstrap, but all yielded the same results.

**Comment by zennef** [comment]
even though you updated it, I'm stuck at this point where after you click "toggle" it slides open and then the content just appears. What do I need to do to get the content to slide open with the menu rather than just having it appear after the menu is done sliding?
