### ISSUE TITLE
closing after rendering

### ISSUE THREAD

**Issue by clodny** [danielepiccone/ng-pageslide#152]
I've noticed one isssue. If initially set psOpen to false, panel is open and closes only after psOpen watcher works, instead of being closed initially.

**Comment by randellhodges** [comment]
I see that too. Do you have a workaround? I'm playing around with it now to see if I can figure something out.

**Comment by rjmacarthy** [comment]
I have this problem,

**Comment by windmaomao** [comment]
why not just add this to the core 

slider.style.right = "-" + param.size;

so that we don't have the bug any more ?

**Comment by danielepiccone** [comment]
version 2.2.0 should address this issue
