### ISSUE TITLE
ps-open is not working as expected

### ISSUE THREAD

**Issue by smasithick** [danielepiccone/ng-pageslide#154]
Hi @dpiccone 

If ps-open is set to false initially, pageslide still open and closes automatically, instead of being closed.

If ps-open is set to true initially, pageslide still open and closes automatically and then it opens again.

It's like a flash, opens and closes irrespective of the ps-open setting.

Please provide us a fix.

**Comment by windmaomao** [comment]
seems to me this line has some issue

```
  el.addClass(param.className);
```

if I comment it out, then the $watch on psOpen works. I have no idea why.

**Comment by bellsenawat** [comment]
I face this problem to :(

**Comment by deini** [comment]
Same

**Comment by danielepiccone** [comment]
Version 2.2.0 should fix this problem as there are some changes to the init cycle
