### ISSUE TITLE
Add a "psBuffer" property for pageslides with drop shadows

### ISSUE THREAD

**Issue by AndrewIsh** [danielepiccone/ng-pageslide#156]
Since the pageslide positions itself off the side of the page by the same number of pixels as it's width, it's a problem if it is styled to have a drop shadow as this is still visible.

I propose adding a psBuffer property that is passed to the directive which specifies how many pixels from the side of the viewport to position itself. I understand that this will introduce an apparent delay while the slideout traverses that distance before it becomes visible, but I'm struggling to think of an alternative.

This is an pretty specialist request and isn't going to affect most people. I'm happy to create a PR for it and submit it.

**Comment by AndrewIsh** [comment]
This has now been submitted: https://github.com/dpiccone/ng-pageslide/pull/157

**Comment by danielepiccone** [comment]
I have left a comment on the PR. I am closing this however since there won't by any other addition to the base API
