### ISSUE TITLE
transition-property: translate()???

### ISSUE THREAD

**Issue by PriyanshDwivedi** [danielepiccone/ng-pageslide#159]
Hi,

I am trying to achieve a 60 fps frame-rate on my new website and I am using this directive for the menu. 
According to [this](https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108#.utedtsxnv) article, the only properties you should be animating are opacity and transform. I was wondering if there is any way to change the transition-property to translateX() so that I can improve the frame-rate of this directive.

Right now, the transition-property applied to ng-pageslide is 'top, bottom, left, right'.

**Comment by danielepiccone** [comment]
This has been waiting since forever but I am not planning any more work on the directive, and this needs a rewrite of the whole opening/closing logic. :disappointed:
