### ISSUE TITLE
Peer angular-pageslide-directive@2.1.3 wants angular@1.5.x

### ISSUE THREAD

**Issue by bellsenawat** [danielepiccone/ng-pageslide#163]
I build project to development and it failed deployment which using angular version 1.6.3

"npm ERR! peerinvalid Peer angular-pageslide-directive@2.1.3 wants angular@1.5.x"

So how to solve this issue in short term.

Change package.json ?

**Comment by rbruce2** [comment]
Use bower install angular-ng-pageslide this should auto resolve your issues.

**Comment by danielepiccone** [comment]
Updated as 2.1.5
