### ISSUE TITLE
Allow other transition properties

### ISSUE THREAD

**Issue by sbowler** [danielepiccone/ng-pageslide#166]
I'd like to be able to specify other transition properties. I use your directive sometime to do more of an expand and collapse sort of thing with the width changing, which used to work find when you transitioned on width and height.

This would also address https://github.com/dpiccone/ng-pageslide/issues/159 . I could probably send a pull request to do this if you'd like, but I'm not sure I'd do it the way you would or if there are any tests I'd also need to write or update, which might be a bit problematic for me.

**Comment by danielepiccone** [comment]
Thanks for this, but as said in #159 no more work is planned for this directive, especially regarding expanding the base API.
