### ISSUE TITLE
Button to animate along with pageslide

### ISSUE THREAD

**Issue by digin8** [danielepiccone/ng-pageslide#50]
Hi there, 

Thanks for pageslide. 

Do you know of any way to get the button to animate preceding the pageslide?

For example, a button (tab?) exists on the edge of the browser window, clicking opens pageslide but the button/tab is still attached to it. Click the button/tab to close.

**Comment by pmMarianP** [comment]
Do you mean a feature similiar to this one?
https://github.com/balysv/material-menu (the 2nd gif)

It's also used in android's "DrawerArrowToggle".

Would be a really nice feature for the pageslide!

**Comment by mapsolon** [comment]
+1

**Comment by dpiccone** [comment]
You can use your psOpen binding to flip between states in an external button like in https://github.com/balysv/material-menu .This doesn't really belong to the pageslide.

However I understand that the button should follow the pageslide movement, that is not possible currently but I think it should, by using the internal content.

**Comment by dpiccone** [comment]
Related to https://github.com/dpiccone/ng-pageslide/issues/41
